### ISSUE TITLE
surrounding mkdir with @ in bootstrap.php cause errors with external tools

### ISSUE THREAD

**Issue by doshu** [mirko-pagliai/php-thumber#18]
unsing @ operator to disable warning in mkdir function call in bootstrap cause some tools, such as deployer, to fail.
the @ operator avoid the emit of a warning, but the warning itself is passwd to the global error handler.

a simple check if the directory exists, should be enough

**Comment by mirko-pagliai** [comment]
Hi @doshu
So you suggest to check if the directory exists and issue a warning otherwise?

**Comment by doshu** [comment]
I suggest to call mkdir only if the directory does not exists, avoiding any
warnings.
The behavior will be the same as now, with the difference that the global
error handler will not be involved.


Il Mar 29 Giu 2021, 18:54 Mirko Pagliai ***@***.***> ha
scritto:

**Comment by mirko-pagliai** [comment]
So check that the directory doesn't already exist, but then check that it's writable too, right?

```
if (!file_exists(THUMBER_TARGET)) {
   mkdir(THUMBER_TARGET, 0777, true);
}
if (!is_writeable(THUMBER_TARGET)) {
    trigger_error(sprintf('Directory `%s` not writeable', THUMBER_TARGET), E_USER_ERROR);
}
```

**Comment by doshu** [comment]
yes, sounds good!

Il giorno mer 30 giu 2021 alle ore 17:11 Mirko Pagliai <
***@***.***> ha scritto:

**Comment by mirko-pagliai** [comment]
Do it!
